### ISSUE TITLE
Выделение активного пункта меню

### ISSUE THREAD

**Issue by dshumko** [akartynnik/Templater#4]
Нет единого стиля отображения активного пункта меню
главное меню. активный пункт выделен пунктиром
![menu](https://cloud.githubusercontent.com/assets/8360276/5991541/ea4b1380-aa05-11e4-8851-38d3e7b261ad.png)
подменю. все пункты выделины пунктиром, а активный не выделен ничем. 
![submenu](https://cloud.githubusercontent.com/assets/8360276/5991542/ea4e6c88-aa05-11e4-94c3-d8f237177427.png)
думаю правильней сделать в подменю выделение как в основном меню.

**Comment by akartynnik** [comment]
окей, сегодня поработаю над этим.

**Comment by akartynnik** [comment]
переработаны шаблоны для версий мантиса 1.2.X. Меню и кнопки сделаны в едином стиле. Ну и вообще много оптимизации. Тестировалось под FF, Chrome. Если вас устроят правки - внесу их в версию для шаблона под 1.3.X

**Comment by akartynnik** [comment]
Шаблоны для версии MantisBT 1.2.X протестированы в IE11, FF 35.0.1, Vivaldi 1.0, Chrome 40.0

**Comment by akartynnik** [comment]
Шаблон для версии готов MantisBT 1.3.X протестирован в IE11, FF 35.0.1, Vivaldi 1.0, Chrome 40.0. Задача закрыта.
